version: 2

sources:
  - name: bronze
    database: grocery_sales
    schema: bronze
    tables:
      - name: train
      - name: test
      - name: stores
      - name: transactions
      - name: oil
      - name: holidays_events
